#ifndef ENTITYCOMPONENT_GLOBAL_H
#define ENTITYCOMPONENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ENTITYCOMPONENT_LIBRARY)
#  define ENTITYCOMPONENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ENTITYCOMPONENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ENTITYCOMPONENT_GLOBAL_H
